Revert "feat(nvim): install vale-ls"
This reverts commit f56fffdb1f3bca9eb84d4b507b3ffe3a806b7cb8.

vale-ls shows diagnostics, but crashes after a few seconds with the
following logs:

[ERROR][2023-10-25 16:07:13] .../vim/lsp/rpc.lua:675    "rpc"   "/home/voreny/.local/share/nvim/mason/bin/vale-ls"      "stderr"        "thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/server.rs:318:61\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"

Maybe I will have better luck using vale from the CLI.